"""Audit original v0.8.3 PNG/WAV bytes and metadata without altering any media."""
from pathlib import Path
import hashlib
import json
import wave
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT/'ArtSource/StorybookV1/V083'

def main():
    manifest = json.loads((SRC/'manifest.json').read_text(encoding='utf-8'))
    assert not manifest['partial'], 'Final audit requires all generated assets'
    assert len(manifest['animations']) == 5 and len(manifest['cards']) == 9 and len(manifest['audio']) == 6
    report = dict(version='0.8.3', date='2026-10-02', sourceImages=[], sounds=[], frameCount=0, unitCount=0)
    for row in manifest['animations']+manifest['cards']:
        path = ROOT/row['file']
        assert hashlib.sha256(path.read_bytes()).hexdigest() == row['sha256'], row['file']
        with Image.open(path) as im:
            assert im.size == (row['width'], row['height'])
            item = dict(file=row['file'], sha256=row['sha256'], width=im.width, height=im.height, mode=im.mode)
            if 'frames' in row:
                alpha = np.asarray(im.getchannel('A'))
                assert np.mean(alpha == 0) > .2
                assert len(row['frames']) == 16
                feet = []
                for frame in row['frames']:
                    x, y = frame['uv']; width, height = frame['size']
                    assert x >= 0 and y >= 0 and width > 0 and height > 0
                    assert x+width <= im.width and y+height <= im.height
                    assert np.count_nonzero(alpha[y:y+height, x:x+width] > 96) > 20
                    feet.append((y+height-frame['pivot'][1])/row['ppu'])
                assert max(feet)-min(feet) < .0001, (row['id'], 'Feet must share one world anchor')
                item['transparentFraction'] = float(np.mean(alpha == 0))
                item['poses'] = len(row['frames'])
                item['groundAnchorWorldOffset'] = feet[0]
                item['groundAnchorSpread'] = max(feet)-min(feet)
                report['frameCount'] += len(row['frames'])
                report['unitCount'] += len(row['unitIds'])
            report['sourceImages'].append(item)
    for row in manifest['sources']:
        generation = row['generation']
        assert generation and generation.get('prompt'), row['id']
        original = Path(generation.get('source', ''))
        if original.is_file():
            assert hashlib.sha256(original.read_bytes()).hexdigest() == row['sha256'], (row['id'], 'Archived PNG must preserve generated bytes')
            matching = next(item for item in report['sourceImages'] if item['file'] == row['file'])
            matching['matchesOriginalGenerationBytes'] = True
    for row in manifest['audio']:
        path = ROOT/row['file']
        assert hashlib.sha256(path.read_bytes()).hexdigest() == row['sha256'], row['key']
        with wave.open(str(path), 'rb') as stream:
            assert (stream.getnchannels(), stream.getsampwidth(), stream.getframerate()) == (1, 2, 48000)
            seconds = stream.getnframes()/stream.getframerate()
            samples = np.frombuffer(stream.readframes(stream.getnframes()), dtype='<i2').astype(float)/32767
        peak = float(np.max(np.abs(samples)))
        peak_db = float(20*np.log10(max(peak, 1.e-12)))
        assert abs(seconds-row['seconds']) < 1/48000
        assert peak < 1 and peak_db <= row['peakDbFS']+.01
        assert abs(float(samples.mean())) < .001
        assert abs(samples[0]) < .0001 and abs(samples[-1]) < .0001
        report['sounds'].append(dict(key=row['key'], file=row['file'], sha256=row['sha256'],
            seconds=seconds, peakDbFS=peak_db, rmsDbFS=float(20*np.log10(max(1.e-12, np.sqrt(np.mean(samples*samples))))),
            sampleRate=48000, channels=1, bits=16, noClipping=True, endpointsFaded=True))
    report['status'] = 'passed'
    report['scope'] = 'source byte hashes, image alpha/frame rectangles, complete prompts and PCM format/levels; no subjective listening claim'
    target = ROOT/'docs/validation/V083Assets-Validation.json'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(report, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    print('V083_ASSET_AUDIT_OK', len(report['sourceImages']), 'PNGs;', report['frameCount'], 'poses;', report['unitCount'], 'unit IDs;', len(report['sounds']), 'WAVs')

if __name__ == '__main__':
    main()
